# Generated by Django 4.1.1 on 2023-08-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promptEngine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="content_type",
            field=models.CharField(default="image/png", max_length=50),
        ),
    ]
